name: Release SDK & UI

env:
  CI: true
  FORCE_COLOR: true

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
        env:
          # Workaround for https://github.com/actions/setup-node/issues/317
          FORCE_COLOR: 0

      - run: yarn install --immutable
      - run: yarn build

      - name: Test SDK & UI
        run: yarn test

      - name: Test SDK integration against live contracts
        if: ${{ github.ref == 'refs/heads/master' }}
        run: yarn test-live

      - name: Release SDK on NPM
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release

      - name: Login to Docker Hub
        uses: azure/docker-login@v2
        if: ${{ github.event_name == 'push' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Release dev-frontend on Docker Hub
        if: ${{ github.event_name == 'push' }}
        run: |
          docker-compose build
          docker-compose push
        working-directory: ./packages/dev-frontend
        env:
          TAG: ${{ fromJSON('{ "refs/heads/master":"latest", "refs/heads/main":"next" }')[github.ref] }}
